Update pipeline to fail

diff --git a/.github/workflows/popcorn.yml b/.github/workflows/popcorn.yml
--- a/.github/workflows/popcorn.yml
+++ b/.github/workflows/popcorn.yml
@@ -26,7 +26,9 @@ jobs:
         working-directory: ./src
         run: |
           ./gradlew popcorn -PerrorReportEnabled --stacktrace
-          echo "$?" >> $GITHUB_OUTPUT
+          if [ "$?" -eq 1]; then
+            echo "failure" >> $GITHUB_OUTPUT  
+          fi
         continue-on-error: true
 
       - name: Read Markdown file
@@ -71,6 +73,6 @@ jobs:
       - name: Fail the job if module analysis has failed
         if: always()  # ensures it runs no matter what
         run: |
-          if [ "${{ steps.module_analysis.outputs.content }}"  -eq 1]; then
+          if [ "${{ steps.module_analysis.outputs.content }}"  == "failure"]; then
             exit 1
           fi
